name: candev_portfolio
description: A new Flutter Web and gh-pages project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  vertical_card_pager: ^1.5.0
  hawk_fab_menu: ^1.1.1
  url_launcher: ^6.0.18

  # app viagens
  font_awesome_flutter: ^9.2.0

  # app floricultura/loja de bolsas/app viagens
  flutter_svg: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/assets/

    # app viagens
    - assets/assets_app_viagens/

    # app floricultura
    - assets/assets_app_floricultura/icons/
    - assets/assets_app_floricultura/images/

    # app conversas
    - assets/assets_app_conversas/

    # app loja de bolsas
    - assets/assets_app_loja_bolsas/icons/
    - assets/assets_app_loja_bolsas/images/

  fonts:
    - family: "Bevan"
      fonts:
        - asset: assets/fonts/Bevan-Regular.ttf
