name: Candev
description: A new Flutter Web and gh-pages project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.5
  vertical_card_pager: ^1.5.0
  hawk_fab_menu: ^1.2.0
  url_launcher: ^6.1.10
  lottie: ^2.3.0
  wordpress_client: ^6.3.4
  flutter_html: 3.0.0-alpha.6

  # app viagens
  font_awesome_flutter: ^10.4.0

  # app floricultura/loja de bolsas/app viagens
  flutter_svg: ^2.0.4

  # app loja de roupas
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/assets/logo-CD-Candev.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/assets/logo-CD-Candev.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/assets/logo-CD-Candev.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/assets/logo-CD-Candev.png"

flutter:

  uses-material-design: true

  assets:
    - assets/assets/

    # app viagens
    - assets/assets_app_viagens/

    # app floricultura
    - assets/assets_app_floricultura/icons/
    - assets/assets_app_floricultura/images/

    # app conversas
    - assets/assets_app_conversas/

    # app loja de bolsas
    - assets/assets_app_loja_bolsas/icons/
    - assets/assets_app_loja_bolsas/images/

    # app loja de roupas
    - assets/assets_app_loja_roupas/icons/
    - assets/assets_app_loja_roupas/images/

  fonts:
    - family: "Bevan"
      fonts:
        - asset: assets/fonts/Bevan-Regular.ttf
    - family: "Neuropolitical Rg"
      fonts:
        - asset: assets/fonts/Neuropolitical_Rg.ttf
